### ISSUE TITLE
get all pins with originals urls

### ISSUE THREAD

**Issue by thewayur** [shadow-prince/pinterest-scrapper-express#3]
How to fetch all pins in a board with originals urls?

to get original urls [i had to change index.js:L99 code from](https://github.com/shadow-prince/pinterest-scrapper-express/blob/e1373f4997b34e168dfa84e031bf8fb893552d73/index.js#L99)
`_a.toString().replace(re, "564x")`
to
`_a.toString().replace(re, "originals")`

but how to get all pins?

**Comment by shadow-prince** [comment]
Good work!
> `_a.toString().replace(re, "564x")`
> to
> `_a.toString().replace(re, "originals")`
> 

We need to use either puppeteer or selenium to load entire page & scrape all the pins

**Comment by thewayur** [comment]
@shadow-prince so this library will help to do that?
or it is better to write own code from scratch?

**Comment by shadow-prince** [comment]
- No! It'll take a while for me to work on it  
   > @shadow-prince so this library will help to do that?



- Official API limiting access to first 50 pins! Lemme know if you achieve it. I'm looking forward to it! 😊
   > or it is better to write own code from scratch?

**Comment by thewayur** [comment]
@shadow-prince you r using official developer api?

well all i was able to achieve it by scrapping :D 

my pinterest developer app request is still pending, so i am here for alternate ways

if u r planning to fetch all the pins, it will be helpful for all of us!
thanks in advance!

**Comment by shadow-prince** [comment]
Yes!! For one of my personal full stack app and guess what! My app request is still **pending** too and tired of searching for APIs.. so I created this scrapper and I'm using this with **[wayScript](https://wayscript.com/)** and **firebase** to store pins urls
> @shadow-prince you r using official developer api?
> my pinterest developer app request is still pending, so i am here for alternate ways

No problem! Explain your project idea.. I will try to help as much as I can

**Comment by thewayur** [comment]
Sure,
scraping is not a big deal these days haha,
well i have dirty coded php to scrap, after analyzing behavior of pinterest. i am happy with it.

i am just trying to find a more optimized library for same. and i found ur library.
glad to have it. expand it more. best wishes :)

**Comment by shadow-prince** [comment]
I'll for sure! ThankYou 😊
